In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

<h1>Data Discription</h1>
The data has been split into two groups:
- training set (train.csv)
- test set (test.csv)
    
The training set should be used to build your machine learning models. *Train.csv* dataset have 891 Passengers Information including their names, ticket information, and whether they survived or not.

Like *Train.csv*, there is another dataset named *test.csv* that have 418 passengers infromation but not include that a passenger is survived or not. This data set hide survived information because this dataset is used for testing after creating prediction model using *Train.csv*.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [ ]:
filename = '/kaggle/input/titanic/train.csv'

In [ ]:
df = pd.read_csv(filename)

In [ ]:
df.head(5)

**Description of Columns**

1. PassengerId: Unique IDs for passengers.
2. Survived: Survival status (1 = survived, 0 = died).
3. Pclass: Passenger class (1, 2, 3).
4. Name: Passenger names.
5. Sex: Gender (male, female).
6. Age: Passenger ages.
7. SibSp: Number of siblings/spouses aboard.
8. Parch: Number of parents/children aboard.
9. Ticket: Ticket numbers.
10. Fare: Fare paid.
11. Cabin: Cabin numbers.
12. Embarked: Port of embarkation (C = Cherbourg, Q = Queenstown, S = Southampton).

In [ ]:
df.info()

## Column Type

- PassengerId -> Numerical
- Survived -> Numerical
- Pclass -> Categorical
- Name -> Mixed
- Sex -> Categorical
- Age -> Numerical 
- SibSp -> Categorical
- Parch -> Categorical 
- Ticket -> Mixed
- Fare -> Numerical 
- Cabin -> Mixed
- Embarked -> Categorical

# Univeriant Analysis

## Age

**Conclusions**
- Age is normaly(almost) distributed
- Age have some outlires
- 20% values of age is missing

In [ ]:
df['Age'].describe()

In [ ]:
plt.figure(figsize=(10, 6))
df['Age'].plot(kind='hist', color=plt.cm.viridis(0.5), alpha=0.7)
plt.xlabel('Ages')
plt.title('Distribution of Age')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Age'].plot(kind='kde',color='#1f77b4', linewidth=2)
plt.xlabel('Ages')
plt.title('Distribution of Ages')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Age'].plot(kind='box',color={'whiskers': '#9467bd', 'caps': '#8c564b', 'boxes': '#e377c2', 'medians': '#d62728'})
plt.title('Box plot for ages')
plt.ylabel('Values')
plt.show()

In [ ]:
df[df['Age'] > 65]

In [ ]:
df['Age'].isnull().sum()/len(df['Age'])

## Fare

**Conclusions**
- This Data Highly (Positively) skewed.
- This Data 0% Missing Values.
- Fare col actualy contain the group fare not indivisual (That might be issue).

In [ ]:
df['Fare'].describe()

In [ ]:
plt.figure(figsize=(10, 6))
df['Fare'].plot(kind='hist',bins=20,color=plt.cm.viridis(0.5), alpha=0.7)
plt.xlabel('Fare')
plt.title('Distribution of Fare')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Fare'].plot(kind='kde',color=plt.cm.viridis(0.5), alpha=0.7,linewidth=2)
plt.xlabel('Fare')
plt.title('Distribution of Fare')
plt.show()

In [ ]:
df['Fare'].skew()

In [ ]:
plt.figure(figsize=(10, 6))
df['Fare'].plot(kind='box',color={'whiskers': '#9467bd', 'caps': '#8c564b', 'boxes': '#e377c2', 'medians': '#d62728'})
plt.ylabel('Values')
plt.title('Box plot on Fare')
plt.show()

In [ ]:
df[df['Fare'] > 270]

In [ ]:
df['Fare'].isnull().sum()

## Survived
**Conclusions**
- Almost 60.6% peoples are died and 39.4% are saved.
- There are no missing values in this column.

In [ ]:
df['Survived'].value_counts()

In [ ]:
df['Survived'].value_counts().plot(kind='bar',color=plt.cm.viridis(0.5), alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Survived people in Tiatanic')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Survived'].value_counts().plot(kind='pie',autopct='%0.1f%%',colors=[plt.cm.viridis(0.5),'#9467bd'])
plt.title('Survived people in Tiatanic')
plt.show()

In [ ]:
df['Survived'].isnull().sum()

## Pclass
**Conclusion**
- No Missing values in this column
- 1 class have more cost and 2 class lower then 1 and 3 is lower cost then 1 and 2. But Surprisely Peoples in class 2 is lower then class 1.

In [ ]:
df['Pclass'].value_counts()

In [ ]:
df['Pclass'].value_counts().plot(kind='bar',color=plt.cm.viridis(0.5), alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Class Wise peoples in Titanic')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Pclass'].value_counts().plot(kind='pie',autopct='%0.1f%%',colors=[plt.cm.viridis(0.5),'#9467bd','#d62728'])
plt.title('Class Wise peoples in Titanic')
plt.show()

In [ ]:
df['Pclass'].isnull().sum()

## Sex
**Conclusions**
- There is no missing values in this column.
- Number of Males are greater then Females. Its not surprise. Generally this sanrio is happned.

In [ ]:
df['Sex'].value_counts()

In [ ]:
df['Sex'].value_counts().plot(kind='bar',color=plt.cm.viridis(0.5), alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Gender wise peoples in Titanic')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Sex'].value_counts().plot(kind='pie',autopct='%0.1f%%',colors=[plt.cm.viridis(0.5),'#9467bd'])
plt.title('Gender wise peoples in Titanic')
plt.show()

In [ ]:
df['Sex'].isnull().sum()

## SibSp & Parch
**Conclusions**
- We can create a family_size column rather then by merging two different columns SibSp and Parch
- We can create a column is_alone.
- There are no missing values in these columns.
- Max num of Passengers are travel alone.

In [ ]:
df['SibSp'].value_counts()

In [ ]:

df['Parch'].value_counts()

In [ ]:
plt.figure(figsize=(10, 6))
df['SibSp'].value_counts().plot(kind='bar',color=plt.cm.viridis(0.5), alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Travel with Number of Siblings')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Parch'].value_counts().plot(kind='bar',color=plt.cm.viridis(0.5), alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Travel with Number of Parent and Childs')
plt.show()

In [ ]:
temp = df['SibSp'].value_counts()
explode = [0, 0.1, 0.3, 0.4, 0.5, 0.6,0.7]
plt.figure(figsize=(10, 6))
plt.pie(temp,labels=temp.index,explode=explode,autopct='%0.1f%%')
plt.title('Travel with Number of Siblings')
plt.show()

In [ ]:
sibsp_counts = df['Parch'].value_counts()
sibsp_counts

explode = [0, 0.1, 0.3, 0.4, 0.5, 0.6,0.7,0.8]
plt.pie(sibsp_counts, labels=sibsp_counts.index, autopct='%0.1f%%', explode=explode)
plt.title("Travel with Number of Parents/Children")
plt.axis('equal')  
plt.show()

In [ ]:
df['SibSp'].isnull().sum()

In [ ]:
df['Parch'].isnull().sum()

## Embarked
**Conclusions**
- There are 2 missing values in this column.

In [ ]:
df['Embarked'].value_counts()

In [ ]:
df['Embarked'].value_counts().plot(kind='bar',color=plt.cm.viridis(0.5), alpha=0.7)
plt.ylabel('No of peoples')
plt.title('No of Peoples embarking from these Ports')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
df['Embarked'].value_counts().plot(kind='pie',autopct='%0.1f%%')
plt.title('No of Peoples embarking from these Ports')
plt.show()

In [ ]:
df['Embarked'].isnull().sum()

# Bivariate Analysis

## Survived and Pclass
**Conclusions**
- Class 3 is more dangerouse because 75% peoples are deid who are in Class 3

In [ ]:
survived_vs_pclass = pd.crosstab(df['Pclass'],df['Survived'],normalize='columns')*100
survived_vs_pclass

In [ ]:
plt.figure(figsize=(10, 6))
sns.heatmap(pd.crosstab(df['Pclass'],df['Survived'],normalize='columns')*100)
plt.title('Pclass vs survived heatmap')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
survived_vs_pclass.plot(kind='bar',stacked=True,color=[plt.cm.viridis(0.5),'#9467bd'], alpha=0.7)
plt.title('Class wise Survived')
plt.show()

## Survived and Sex
**Conclusions**
- The chance of survived of female is more then a male.

In [ ]:
survived_vs_sex = pd.crosstab(df['Sex'],df['Survived'],normalize='columns') * 100
survived_vs_sex

In [ ]:
plt.figure(figsize=(10, 6))
sns.heatmap(survived_vs_sex)
plt.ylabel('No of peoples')
plt.title('Survived vs Gender Heatmap')
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
survived_vs_sex.plot(kind='bar',stacked=True,color=[plt.cm.viridis(0.5),'#9467bd'], alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Gender wise Survived')
plt.show()

## Survived and Embarked
**Conclusion**
- This is no matter which passinger from which embarked that died but here in C Station peoples are more survived rather then other stations (Q and S). There are two assumptions:
1. May be females are more from Stations C
2. May be more peoples from C in Class 1 (True)

In [ ]:
survived_vs_embarked = pd.crosstab(df['Survived'],df['Embarked'],normalize='columns')*100
survived_vs_embarked

In [ ]:
plt.figure(figsize=(10, 6))
survived_vs_embarked.plot(kind='bar',stacked=True,color=[plt.cm.viridis(0.5),'#9467bd','#d62728'], alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Class wise Survived')
plt.show()

In [ ]:
pd.crosstab(df['Sex'],df['Embarked'],normalize='columns')*100

In [ ]:
pd.crosstab(df['Pclass'],df['Embarked'],normalize='columns')*100

## Survived and Age

In [ ]:
plt.figure(figsize=(10, 6))
df[df['Survived'] == 0]['Age'].plot(kind='kde',label='Not Survived')
df[df['Survived'] == 1]['Age'].plot(kind='kde',label='Survived')
plt.legend()
plt.xlabel('Ages')
plt.title('Ages wise Survived')
plt.show()

# Feature Engineering

In [ ]:
df['SibSp'].value_counts()

In [ ]:
df[df['SibSp'] == 8]

**Conclusion**
- Here is mistake because Passenger have 9 family members including itself. But here only 7 show.
- Maybe other family members in test.csv dataframe. (True)

In [ ]:
df1 = pd.read_csv('/kaggle/input/titanic/test.csv')

In [ ]:
df = pd.concat([df,df1])

In [ ]:
df[df['SibSp'] == 8]

**Conclusion**
- The Other family members that are not present in train.csv are present in test.csv.

In [ ]:
df['indivisual_fare'] = df['Fare'] / (df['SibSp'] + df['Parch'] + 1)

In [ ]:
df['family_size'] = df['SibSp'] + df['Parch'] + 1

**Create Family Type Column**
* if family_size == 1    -> alone
* if family_size == 2-3  -> small
* if family_size > 3     -> large

In [ ]:
def transform_family_size(num):
    if num == 1:
        return 'alone'
    elif num > 1 and num < 4:
        return 'small'
    else:
        return 'large'

In [ ]:
df['family_type'] = df['family_size'].apply(transform_family_size)

In [ ]:
df.sample()

**Make Two New Columns using name Column**
1. Surname
2. Title

In [ ]:
df['Surname'] = df['Name'].str.split(',').str.get(0)

In [ ]:
df['Title'] = df['Name'].str.split(',').str.get(1).str.strip().str.split(' ').str.get(0)

In [ ]:
df['Title'].value_counts()

In [ ]:
df['Title']=df['Title'].replace(['Jonkheer.','the','Capt.','Don.','Major.','Col.','Dr.','Rev.'],'Others')

In [ ]:
df['Title']=df['Title'].replace({'Mlle.':'Miss.','Mme.':'Mrs.','Done.':'Mrs.'})

In [ ]:
df['Title'].value_counts()

In [ ]:
df['Cabin'].isnull().sum()

In [ ]:
df['Cabin'] = df['Cabin'].fillna('M')

**Conclusion**
- M will presents missing values

In [ ]:
df['Deck'] = df['Cabin'].str[0]

# EDA After Feature Engineering

In [ ]:
# family_vs_survived = pd.crosstab(df['family_type'],df['Survived'],normalize='columns')*100
family_vs_survived=pd.crosstab(df['Survived'],df['family_type'],normalize='columns')*100
family_vs_survived

In [ ]:
plt.figure(figsize=(10, 6))
family_vs_survived.plot(kind='bar',stacked=True,color=[plt.cm.viridis(0.5),'#9467bd','#d62728'], alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Family Type wise Survived')
plt.show()

In [ ]:
title_vs_survived = pd.crosstab(df['Survived'],df['Title'],normalize='columns')*100
title_vs_survived

In [ ]:
plt.figure(figsize=(10, 6))
title_vs_survived.plot(kind='bar',stacked=True)
plt.ylabel('No of peoples')
plt.title('Title wise Survived')
plt.show()

In [ ]:
deck_vs_survived = pd.crosstab(df['Deck'],df['Survived'],normalize='index')*100

In [ ]:
plt.figure(figsize=(10, 6))
deck_vs_survived.plot(kind='bar',stacked=True,color=[plt.cm.viridis(0.5),'#9467bd'], alpha=0.7)
plt.ylabel('No of peoples')
plt.title('Deck wise Survived')
plt.show()

In [ ]:
df.head(4)

In [ ]:
f, ax = plt.subplots(figsize=(10, 6))
corr = df[['Survived','Pclass','Age','SibSp','Parch','Fare']].corr()
sns.heatmap(corr,
            mask=np.zeros_like(corr, dtype=bool), 
            cmap=sns.diverging_palette(220, 10, as_cmap=True),
            square=True, ax=ax)